# Generated by Django 3.0.2 on 2020-02-14 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('product_desc', models.CharField(max_length=2000)),
                ('contract_num', models.IntegerField(default=0)),
                ('sinistro_num', models.IntegerField(default=0)),
                ('access_num', models.IntegerField(default=0)),
                ('gps_location', models.BooleanField(default=False)),
                ('map_structure', models.BooleanField(default=False)),
                ('timer_disposal', models.BooleanField(default=False)),
                ('timer_display', models.IntegerField(default=0)),
                ('preco_display', models.BooleanField(default=False)),
                ('preco_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('saldo_num', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(to='ProdCreate.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('num_produtos', models.IntegerField(default=0)),
                ('num_riscos', models.IntegerField(default=0)),
                ('num_contracts', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(to='ProdCreate.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='belongs_to',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='Seguradora', to='ProdCreate.Seguradora'),
        ),
    ]
